kind: Namespace
apiVersion: v1
metadata:
  name: metabase

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: metabase  
data:
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: database-name
  MB_DB_PORT: "5432"
  MB_DB_USER: user
  MB_DB_PASS: password
  MB_DB_HOST: database-hostname

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: metabase  
  labels:
    name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metabase
  template:
    metadata:
      labels:
        name: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:v0.44.2
        env:
            - name: TZ
              value: America/Sao_Paulo         
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: metabase-config
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
---

apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase  
spec:
  selector:
    name: metabase
  ports:
  - port: 3000
    targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: metabase
  namespace: metabase
spec:
  tls:
  - hosts:
    - metabase.your-domain.com.br
  rules:
  - host: metabase.your-domain.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metabase
            port: 
              number: 3000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: metabase-hpa
  namespace: metabase
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metabase
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90              